abstract: Plot the Detailed Structure of Makefiles Using GraphViz
author: 'Agent Zhang <agentzh@gmail.com>'
build_requires:
  File::Compare: 1.1003
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Makefile-GraphViz
no_index:
  directory:
    - script
    - samples
    - inc
    - t
requires:
  GraphViz: 2.02
  Makefile::Parser: 0.11
  perl: 5.6.1
version: 0.11
